### ISSUE TITLE
Request defining 'BOF' right on the schedule page

### ISSUE THREAD

**Issue by Michael-S** [perlconference/tpc-2020-cloud#1]
I found the 'Birds of a Feather' definition right on the Wiki page, but it seems odd that I had to hunt for it.  Maybe 'BOF' is a common reference among Perl community conference veterans, but as a newbie it felt odd to hit a term I didn't know on the very first item in the conference schedule.

**Comment by toddr** [comment]
I have updated the description. Hopefully that will help future folks?

**Comment by Michael-S** [comment]
Thank you!
